In [4]:
import numpy as np

# Create an array
arr = np.arange(12).reshape(3, 4)

print(arr)
# Basic operations
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))

# Reshaping and transposing
print("Transposed:\n", arr.T)

# Mathematical operations
print("Exponential:", np.exp(arr))

# Linear algebra
b = np.array([1, 2, 3])
x = np.linalg.solve(arr[:3, :3], b)
print("Solution to linear equations:", x)

# Advanced indexing
print("Even numbers:", arr[arr % 2 == 0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Sum: 66
Mean: 5.5
Transposed:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Exponential: [[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


LinAlgError: Singular matrix

In [ ]:
import numpy as np

# Create a singular matrix
singular_matrix = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]])

# Try to solve a system of equations
b = np.array([1, 2, 3])

try:
    x = np.linalg.solve(singular_matrix, b)
except np.linalg.LinAlgError as e:
    print(f"Error: {e}")
    
# Check if the matrix is singular
print(f"Determinant: {np.linalg.det(singular_matrix)}")


if np.linalg.det(matrix) == 0:
    print("Matrix is singular")
else:
    # Proceed with your operation

In [ ]:
x = np.linalg.pinv(singular_matrix).dot(b)

print(non_singular = singular_matrix + np.eye(singular_matrix.shape[0]) * 1e-5)

In [5]:
import numpy as np

# Create sample 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Create sample 2D arrays
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])

In [6]:
# 1D arrays
d_stack_1d = np.dstack((a, b))
print("Depth stack of 1D arrays:\n", d_stack_1d)

# 2D arrays
d_stack_2d = np.dstack((c, d))
print("Depth stack of 2D arrays:\n", d_stack_2d)

Depth stack of 1D arrays:
 [[[1 4]
  [2 5]
  [3 6]]]
Depth stack of 2D arrays:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [ ]:
# 1D arrays
d_stack_1d = np.dstack((a, b))
print("Depth stack of 1D arrays:\n", d_stack_1d)

# 2D arrays
d_stack_2d = np.dstack((c, d))
print("Depth stack of 2D arrays:\n", d_stack_2d)

In [10]:
import numpy as np

# Example 1: Simple 2D block (this remains unchanged)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.block([[a], [b]])
print("Block example 1:\n", c)

# Example 2: More complex blocking (corrected)
a = np.array([[1, 2], [3, 4]])  # 2x2 array
b = np.array([[5, 6], [7, 8]])  # 2x2 array
d = np.zeros((2, 3))            # 2x3 array
e = np.ones((2, 3))             # Changed to 2x3 array to match the width of 'd'
f = np.block([[a, d], [b, e]])
print("\nBlock example 2:\n", f)

Block example 1:
 [[1 2]
 [3 4]
 [5 6]]

Block example 2:
 [[1. 2. 0. 0. 0.]
 [3. 4. 0. 0. 0.]
 [5. 6. 1. 1. 1.]
 [7. 8. 1. 1. 1.]]
