In [1]:
import numpy as np

# Creating sample student data
students = {
    'Name': ['John', 'Emma', 'Michael', 'Sarah', 'David', 'Lisa'],
    'Math_Score': [85, 92, 78, 95, 88, 90],
    'Science_Score': [88, 85, 92, 89, 94, 87],
    'English_Score': [90, 88, 85, 92, 86, 91]
}

# Converting scores into a 2D numpy array
scores_array = np.array([
    students['Math_Score'],
    students['Science_Score'],
    students['English_Score']
]).T

print("2D Array of Scores (Each row represents a student's scores):")
print(scores_array)
print("\nShape of array:", scores_array.shape)

# Calculating mean for each subject
subject_means = np.mean(scores_array, axis=0)
print("\nMean Scores:")
print(f"Math: {subject_means[0]:.2f}")
print(f"Science: {subject_means[1]:.2f}")
print(f"English: {subject_means[2]:.2f}")

# Calculating total score for each student
total_scores = np.sum(scores_array, axis=1)
print("\nTotal Scores for each student:")
for name, score in zip(students['Name'], total_scores):
    print(f"{name}: {score}")

# Finding highest total score
highest_score_index = np.argmax(total_scores)
print(f"\nStudent with highest total score: {students['Name'][highest_score_index]}")
print(f"Highest total score: {total_scores[highest_score_index]}")

2D Array of Scores (Each row represents a student's scores):
[[85 88 90]
 [92 85 88]
 [78 92 85]
 [95 89 92]
 [88 94 86]
 [90 87 91]]

Shape of array: (6, 3)

Mean Scores:
Math: 88.00
Science: 89.17
English: 88.67

Total Scores for each student:
John: 263
Emma: 265
Michael: 255
Sarah: 276
David: 268
Lisa: 268

Student with highest total score: Sarah
Highest total score: 276
